- src/he/plugin_chain.c
- test/he/test_plugin_chain.c
Fix a memory leak when releasing plugin chains
Contains autotests and compiled locally with `ceedling test project:macos`
> plugin: fix memory leak when freeing plugin chains

- src/he/conn.c
- src/he/conn.h
We make a copy inside so the buffer passed should be const.
> conn: const correct setting auth buffers

- src/he/msg_handlers.c
- test/he/test_msg_handlers.c
Check auth buffer length is valid before passing to the user provided `auth_buffer_cb` callback.
Prevent potential out-of-bound read in the user provided code.
I've added a unit test for this fix.
> msg_handlers: check auth buffer length before passing to auth_buffer_cb

- project.yml
- test/support/wolfssl_testable_types.h
- unix.yml
- windows_32.yml
- windows_64.yml
* Use version 5.2.0 of WolfSSL
* Add mock struct for new WolfSSL type (`WOLFSSL_X509_EXTENSION`)
* Add `va_list` to `treat as array` list for test generation
Brings WolfSSL up to date.
Test suite as part of `earthly +all` completes successfully
> Upgrade WolfSSL to 5.2.0

- include/he.h
- public/he.h
- src/he/conn.c
- src/he/conn.h
- src/he/msg_handlers.c
- test/he/test_conn.c
- test/he/test_msg_handlers.c
- test/support/test_defs.h
* Added a new error code: `HE_ERR_INVALID_AUTH_TYPE`. Client-side code may see this error when the `conn->auth_type` is set to unsupported value.
* Deprecate `he_conn_set_auth_buffer`. Client-side code should use `he_conn_set_auth_buffer2` instead. And both function will set the `auth_type` to `HE_AUTH_TYPE_CB`.
* Server-side code will response "Access Denied" if the auth message contains unsupported `auth_type`.
Previously, a Lightway client can set any value to the `auth_type` field in the authentication message sent to the server, then the server side code just consider it's using "auth_buffer" without actually checking the value of auth_type. By using a specific code for the "auth buffer based" authentication, we can add support to more `auth_type` in the future.
All changes have been …
> Add new auth type (HE_AUTH_TYPE_CB) and deprecate he_conn_set_auth_buffer

- windows/wolfssl.vcxproj
Update the wolfssl.vcxproj for WolfSLL v5.2.0.
Lightway Core requires a few extra CFLAGS to be set while compiling WolfSSL, however we can't override the settings of Visual Studio project from command-line, so we have to patch the `wolfssl.vcxproj` file each time when we bump WolfSSL.
The change has been tested on a Windows device via running `ceedling project:windows_32`.
> Update WolfSSL Visual Studio project file

- src/he/conn.c
- src/he/flow.c
- test/he/test_conn.c
- test/he/test_flow.c
Improved error handling when calling `wolfSSL_read` and `wolfSSL_write`.
According to wolfSSL documentation, we should always call `wolfSSL_get_error()` when [`wolfSSL_write`](https://www.wolfssl.com/doxygen/group__IO.html#gad6cbb3cb90e4d606e9507e4ec06197df) / [`wolfSSL_read`](https://www.wolfssl.com/doxygen/group__IO.html#ga80c3ccd3c0441c77307df3afe88a5c35) returns <= 0. And [`wolfSSL_get_error`](https://www.wolfssl.com/doxygen/group__Debug.html#gaafd5671d443fa684913ba5955a4eb591) may return `SSL_ERROR_NONE` in some cases:
> SSL_ERROR_NONE will be returned if ret > 0. For ret <= 0, there are some cases when this value can also be returned when a previous API appeared to return an error code but no error actually occurred. An example is calling …
> Improve error handling when calling wolfSSL_read and wolfSSL_write

- src/he/conn.c
- test/he/test_conn.c
Send goodbye messages on more states
Prevents servers from thinking that the connection is active when in fact the user has already disconnected
> conn: send goodbye messages on more states

- Earthfile
Adds a version number to prevent an earthly warning and uses the latest debian for builds
Manually tested with `earthly +all`
> build: use bullseye image for builds

- .github/workflows/ci.yml
- public/he.h
- src/he/conn.h
- test/he/test_conn.c
- test/he/test_plugin_chain.c
- windows_64.yml
Fix unit tests on Windows.
The tests were broken on windows because Ceedling / CMock couldn't process the `HE_DEPRECATE` C macro properly. We have to remove it from `he.h` and `conn.h` to workaround it. Unfortunately that means we cannot warn users of the deprecated `he_conn_set_auth_buffer` function to switch to `he_conn_set_auth_buffer2` anymore.
This PR also fixed another issue in test code which used non-standard way to initialize C struct which also breaks the windows test build.
> Fix windows tests

- linux.yml
- linux_386.yml
- linux_arm.yml
- macos.yml
- macos_arm64.yml
- unix.yml
Use O3 Optimizations, increase MAC deployment target and disable wolfssl examples
- We build some repositories with O3 and some with O2, On gcc O2 does not autovectorize but O3 does.
- Mac deployment target will prevent a warning
- Disable wolfssl examples as we do not use them
> Build: Update build flags

- src/he/client.h
- src/he/conn.h
- test/he/test_conn.c
Reduce the renegotiation multiplier to 100 to match the initial connect multiplier
We want to reduce the amount of time it takes before the renegotiation timer gives up. Prior to
this change it takes 127 seconds before it gives up this reduces it to a more reasonable 12.7 seconds.
- No manual testing performed CI, is enough here
> Reduce multiplier for renegotiation timers

- macos.yml
Fix deployment target to 10.10, previously it was interpreted as 10.1
The number gets interpreted as a double instead of a string.
So adding quotes fixes the deployment target.
Tested locally with ceedling
> macos: Fix deployment target

- ios/autotools-ios-helper.sh
The current target does not work on older iphones, The build will have SSL errors
This is due to wolfSSL changing their defaults. `--sp-math-all` is now the default implementation
The iphone tested here was an iphone 6S
This option does not work for older iphones and will result in lack of ability to connect
Without this change older iphones would not connect
Tested internally manually with an iPhone 6S
> ios: Fix builds for older iPhones

- android.yml
- ios/autotools-ios-helper.sh
- linux.yml
- linux_386.yml
- linux_arm.yml
- macos.yml
- macos_arm64.yml
Explicitly enable 4096 SP, this is automatically enabled on x64 but not on 32bit which causes issues with RSA4096. So explicitly enable it to not rely on implicit behaviours
Fixes issues with 32bit builds
Manually tested with android on x86 emu
> wolf: explicitly enable 4096 sp

- include/he.h
- public/he.h
- src/he/conn.c
- src/he/conn.h
- src/he/flow.c
- src/he/msg_handlers.c
- src/he/msg_handlers.h
- src/he/ssl_ctx.c
- src/he/ssl_ctx.h
- test/he/test_conn.c
- test/he/test_msg_handlers.c
- test/he/test_ssl_ctx.c
- test/support/test_defs.h
This PR introduces a new message type `HE_MSGID_SERVER_CONFIG` to allow server pushing any server configuation data to client through the TLS connection.
On the server side, the server can call `he_conn_send_server_config` any time after the state has changed to `LINK_UP`. 
On the client side, the client can set the `he_server_config_cb_t` callback on the connection context to handle this message. This is optional.
The format of server config data is completely opaque to the Lightway Core. It's up to the implementation to define.
This change is unit tested.
> Add new message type: HE_MSGID_SERVER_CONFIG

- include/he.h
- public/he.h
- src/he/conn.h
- src/he/ssl_ctx.c
- src/he/ssl_ctx.h
- test/he/test_ssl_ctx.c
...and fixed some minor typos.
Previous [PR](https://github.com/expressvpn/lightway-core/pull/58) introduced a change to the wire protocol, therefore we should bump the wire protocol version too.
We should also make the constants available to implementations.
Unit tests.
> Make default constants public and bump maximum wire protocol version to 1.2

- public/he.h
- src/he/ssl_ctx.c
- src/he/ssl_ctx.h
- test/he/test_ssl_ctx.c
Allow server implementations to set the minimum / maximum supported wire protocol versions at runtime.
Unit tests.
> Add helper functions for setting min/max supported wire protocol versions on ssl_ctx

- android.yml
- ios.yml
- ios/autotools-ios-helper.sh
- linux.yml
- linux_386.yml
- linux_arm.yml
- macos.yml
- macos_arm64.yml
- project.yml
...also fixed the line ending (from CR/LF to LF) and formatted the project.yml files.
Improve memory safety. See: https://developers.redhat.com/blog/2021/04/16/broadening-compiler-checks-for-buffer-overflows-in-_fortify_source
Note: the equivalent of _FORTIFY_SOURCE on Windows is `/RTCs` (https://learn.microsoft.com/en-us/cpp/build/reference/rtc-run-time-error-checks?view=msvc-170), however it automatically disable optimizations so it can be only used on development build, cannot be used on release builds. Therefore I'm not going to change the Windows build here. 
Unit tested.
> Add -D_FORTIFY_SOURCE=2 when building lightway-core

- src/he/ssl_ctx.c
- test/he/test_ssl_ctx.c
Set the ciphers offered by the servers
This prevents any clients from attempting to connect with weak ciphers
Manually tested with internal tools
> ssl: Set cipher list on servers

- .github/workflows/ci.yml
Github Actions recently bumped the `ubuntu-latest` image to Ubuntu 22.04 which breaks our Linux builds on arms. This change pins the CI image to Ubuntu 20.04 and run `apt update` when installing arm build tools.
N/A.
> ci: fix linux build on arm architectures

- public/he.h
- src/he/conn.c
- src/he/conn.h
- src/he/ssl_ctx.c
- test/he/test_conn.c
Return the name of the cipher being used by current ssl session.
Provide additional information for troubleshooting cipher related issues.
Unit tests.
> conn: add a helper function for getting the cipher used by the current ssl session

- android.yml
- include/he.h
- ios/autotools-ios-helper.sh
- linux.yml
- linux_386.yml
- linux_arm.yml
- macos.yml
- macos_arm64.yml
- public/he.h
- src/he/conn.c
- src/he/conn.h
- test/he/test_conn.c
- test/he/test_conn_connect.c
- test/support/test_defs.h
Enable SNI support in WolfSSL and add a new client API for setting the SNI hostname when initiating the TLS connection.
This feature is unit tested.
> Add SNI Support on client side

- windows/wolfssl.vcxproj
- windows_32.yml
- windows_64.yml
The windows build is broken after bump to WolfSSL v5.5.4-stable because the [`dtls.c`](https://github.com/wolfSSL/wolfssl/commit/cfbd061625ec2790ab36e2a912fdd61356a35466) was not included in our patched `wolfss.vcxproj` file. 
To fix this issue, we updated the `wolfssl.vcxproj` file to latest and manually added our `PreprocessorDefinitions` again. We can't simply use the vanilla .vcxproj files from WolfSSL because we have to set some WOLFSSL preprocessor definition which is not straightforward to set from command-line.
Therefore, it's possible that the windows build will be broken again whenever WolfSSL updates the .vcxproj file. We'll investigate later if there's a better, long term solution.
Tested on CI.
> windows: update vcxproj file for fixing WolfSSL Windows build

- src/he/ssl_ctx.c
- test/he/test_ssl_ctx.c
Reverts setting ciphers for TLS / DTLS
We know the root cause of the issue but it requires WolfSSL to make a new release with the fix included.
As such we revert this to unblock ourselves.
This was the original behaviour and will also be tested with internal testing tools later.
> ssl: revert setting cipher on servers

- public/he.h
- src/he/client.c
- src/he/conn.c
- src/he/memory.c
- src/he/memory.h
- src/he/plugin_chain.c
- src/he/ssl_ctx.c
- test/he/test_client.c
- test/he/test_memory.c
- test/he/test_plugin_chain.c
Make the internal memory management api public.
Allow all downstream components using the same memory functions set by the `he_set_allocators`.
Unit tests.
> memory: expose the internal memory management api to public

- Earthfile
- android.yml
- ios.yml
- linux.yml
- linux_386.yml
- linux_arm.yml
- macos.yml
- macos_arm64.yml
- src/he/ssl_ctx.c
- test/he/test_ssl_ctx.c
- unix.yml
- windows_32.yml
- windows_64.yml
- wolfssl/0001-Merge-pull-request-5911-from-julek-wolfssl-DtlsMsgPo.patch
- wolfssl/0001-Merge-pull-request-5932-from-julek-wolfssl-zd15346.patch
Workaround wolfSSL bug related to setting ciphers and secure renegotiation
The current wolfSSL release has a bug when setting ciphers. Since there is no release with the fix we can simply use patches to work around the issue.
Tested using internal integration tests
> wolfssl: patch fix for secure renegotiation bug

- Earthfile
Fix earthly arch to amd64
We can't use arm64 because cmock seems to have issues when generating mocks for wolfSSL on arm.
This allows an m1 user to use earthly.
Tested locally on an m1 macbook
> earthly: fix architecture to amd64

- macos.yml
set target and host for macos x86
This allows the library to be cross compiled from m1
Tested by manually compiling on an m1 mac
> build: set target and host for macos x86

- .github/workflows/ci.yml
CI update to fix linux-386 CI and add CI to all branches so developers can test CI changes easily without opening a PR
CI is currently broken
Change is to CI so CI tests this
> ci: Fix linux-386 CI and run CI on all branches

- src/he/wolf.c
- test/he/test_wolf.c
When optimistically writing packets in `he_wolf_dtls_write`, we were not checking that the callbacks are returning `HE_SUCCESS`. This patches that.
> Check the result when dispatching additional packets in aggressive mode

- linux_arm.yml
- unix.yml
- windows_32.yml
- windows_64.yml
Update WolfSSL v5.6.2-stable. Changes: https://github.com/wolfSSL/wolfssl/releases/tag/v5.6.2-stable
Keeping Lightway dependencies up-to-date.
Tested on Github Actions.
> wolfssl: update wolfssl to v5.6.2-stable

- Earthfile
- android.yml
- ios.yml
- linux.yml
- linux_386.yml
- linux_arm.yml
- macos.yml
- macos_arm64.yml
- tvos.yml
- windows_32.yml
- windows_64.yml
- wolfssl/0001-DoHelloVerifyRequest-only-do-DTLS-1.3-version-check.patch
- wolfssl/0001-DtlsShouldDrop-don-t-ignore-app-data-sent-before-a-S.patch
- wolfssl/0002-DTLS-1.3-move-state-machine-forward-when-HVR-receive.patch
Add patches that are in wolfSSL master but not in a tagged release. Fixes a some dtls downgrade bugs.
This fixes a case where DTLS1.3 client will not downgrade to DTLS1.2 when attempting to connect to a DTLS1.2 server
Tested together with #76 on lightway-laser
> wolfssl: add patches for dtls downgrade bugs

- android.yml
- ios.yml
- linux.yml
- linux_386.yml
- linux_arm.yml
- macos.yml
- macos_arm64.yml
- tvos.yml
- windows_32.yml
- windows_64.yml
- wolfssl/0001-DoHelloVerifyRequest-only-do-DTLS-1.3-version-check.patch
- wolfssl/0002-DTLS-1.3-move-state-machine-forward-when-HVR-receive.patch
- wolfssl/0003-DtlsShouldDrop-don-t-ignore-app-data-sent-before-a-S.patch
- wolfssl/0004-Dtls13GetRnMask-Correctly-get-chacha-counter-on-BE-s.patch
- wolfssl/2000-Rename-utils.c-to-utils.h.patch
- wolfssl/2001-Merge-pull-request-6700-from-julek-wolfssl-dtls13-do.patch
Adds a DTLS patch for fixing the issue where the client would send acks before version negotiation was complete
Patch comes from https://github.com/wolfSSL/wolfssl/pull/6700
This fixes DTLS 1.3 to 1.2 downgrades in certain edge cases
This patch was tested manually.
> wolfssl: add new dtls 1.3 ack patch

- .github/workflows/ci.yml
Add "test:all" task explicitly to all environment instead of using implicit default task.
Previously github actions uses default task “test:all” for building and testing in some environments like linux, linux_32 etc. But after the recent change of adding verbosity to the build step, ceedling does not run the default task, rather expecting the task explicitly.
This causes github ci not to build and test lightway-core:
https://github.com/expressvpn/lightway-core/actions/runs/5995148143/job/16257745272#step:6:2
Also adding task explicitly makes the intention clear, on what are we running.
Tested locally with command:
```c
ceedling project:linux verbosity[4] test:all
```
Verified github actions for all environment build lightway core properly
> ci: add 'test:all' task explicitly

- linux_arm_no_pqc.yml
- public/he.h
- src/he/conn.c
- src/he/he_internal.h
- src/he/ssl_ctx.c
- src/he/ssl_ctx.h
- test/he/test_conn.c
- test/he/test_conn_connect.c
- test/he/test_ssl_ctx.c
Add ability for client to specify PQC Keyshares
This allows the clients to negotiate with hybrid KEMs
Manually tested with internal tooling
> ssl_ctx: add PQC Keyshares

- include/he.h
- public/he.h
- python/c-header.tx
- python/make_header.py
- python/make_public_header.sh
- src/he/ssl_ctx.c
- src/he/ssl_ctx.h
Fixed a pre-existing bug in the public header generator which was revealed by the addition of PQC APIs by #105.
The public header `public/he.h` should be generated correctly. Developer should never need to "patch" the public/he.h manually.
Regenerate the public header using the script and confirmed it produced correct result.
> doc: fix bugs in public header generator

- public/he.h
- src/he/conn.c
- src/he/conn.h
Remove function `he_conn_set_auth_buffer` which has been deprecated since https://github.com/expressvpn/lightway-core/pull/27. 
We recently added a new `HE_AUTH_TYPE_TOKEN` auth type in https://github.com/expressvpn/lightway-core/pull/108. Removing the deprecated function to reduce confusion.
Tested on CI.
> api: remove deprecated function he_conn_set_auth_buffer

- ios.yml
- liboqs/0001-Prefer-arc4random-on-Apple-platforms-1544.patch
- macos.yml
- macos_arm64.yml
- tvos.yml
Adds a patch from liboqs upstream to prevent failures when generating random numbers
We can quite easily reproduce a failure particularly on the iOS platform and this patch removes any possibility of a failure.
Tested with internal tooling
> liboqs: add a patch to use arc4random_buf

- public/he.h
- src/he/config.c
- src/he/config.h
- src/he/conn.c
- src/he/conn.h
- src/he/he_internal.h
- test/he/test_config.c
- test/he/test_conn.c
Use `uint16_t` as the type of `outside_mtu` and prevent setting outside_mtu to a smaller value than `HE_PACKET_OVERHEAD` (114 bytes).
Fix some tech debts and make setting outside mtu much safer.
Unit tested.
> conn: use uint16_t as the type of outside_mtu

- src/he/conn.c
- src/he/he_internal.h
- src/he/msg_handlers.c
- test/he/test_conn.c
- test/he/test_msg_handlers.c
Support identifier and payload in Lightway Ping/Pong messages. The connection will ignore the pong message with a mismatched id.
Also fixed some tech debts:
- Message handler should ignore invalid ping/pong messages
- Message handler should check the return value of he_internal_send_message
This change is backward compatible, but we'll need to rollout the change to server-side first.
Preparation work for adding the Path MTU Discovery feature.
Unit tested.
> LIT-134 Support payload and identifier in ping/pong message

- .github/workflows/ci.yml
- Earthfile
- linux.yml
Added an Earthly ARG `distro` to allow building Lightway Core for different debian distro.
Build lightway-core for both bullseye and bookworm on CI, as we're preparing to upgrade server to bookworm. The bullseye CI build will be removed later.
Workaround a WolfSSL compiling issue by suppressing a gcc 12 warning via `-Wno-error=stringop-overflow`.
See: https://bugs.launchpad.net/ubuntu/+source/gcc-12/+bug/2013140
Maintenance.
CI.
> ci: build lightway-core for both bullseye and bookworm on ci

- Earthfile
- ios/Lightway/Lightway.xcodeproj/project.pbxproj
- public/he.h
- src/he/conn.c
- src/he/he_internal.h
- src/he/msg_handlers.c
- src/he/pmtud.c
- src/he/ssl_ctx.c
- src/he/utils.c
- src/he/utils.h
- test/he/test_conn.c
- test/he/test_conn_connect.c
- test/he/test_msg_handlers.c
- test/he/test_pmtud.c
- test/he/test_ssl_ctx.c
- test/support/test_defs.h
Initial implementation of Path MTU Discovery, based on [RFC 8899](https://datatracker.ietf.org/doc/html/rfc8899).
The Maximum Transmission Unit (MTU) is the largest amount of data that can be transmitted in a single packet on a network. It is a parameter that is determined by the underlying network technology, and can be configured on network devices (such as routers and switches).
The MTU is important because it determines the maximum size of data that can be transmitted across a network without fragmentation. If a packet is larger than the MTU, it is fragmented into smaller packets to be transmitted across the network, and then reassembled at the receiver. Fragmentation can result in additional processing overhead and increased network traffic, which can impact performance.
The goal of …
> LIT-134 Initial implementation of Path MTU Discovery

- src/he/flow.c
- test/he/test_flow.c
There are potential bugs in the `he_conn_inside_packet_received` function when a Lightway plugin is used.
Bug 1: The function checks the ip packet type after the packet is already processed by the plugin. Since a plugin may modify the packet data in any way it wants, it's no guaranteed that the ipv4 header is still preserved.
Fix potential issue when using Lightway with certain plugins.
Unit tested on CI.
> Fix potential bugs in flow.c: he_conn_inside_packet_received

- src/he/flow.c
- src/he/flow.h
- test/he/test_flow.c
A bug caused server sending fragmented packets when it shouldn't. The fixes are:
* Don't fragment if the inside packet size is exactly the same as the `effective_pmtu`
* Don't fragment if the pmtud search hasn't completed, which should effectively disable the fragment feature on the server side 
Bug fix.
CI tested
> LIT-135 Fixed a bug which causes unexpected fragments from server

- ios/autotools-ios-helper.sh
This fixes an issue with p256 and p256 adjacent algorithms.
This fix is a temporary one until a proper fix is implemented in wolfSSL.
This fixes the issues on iOS
Manually tested
> ios: disable inlining when compiling wolfSSL

- src/he/conn.c
The current computation undercounts the frag table size.
Currently we only free 300-ish entries
This computation is easily checked with IDE tooling
> conn: fix computation for frag table size

- src/he/pmtud.c
- src/he/pmtud.h
- test/he/test_pmtud.c
Retry pmtu check after a minute when the pmtud state goes to `error`
Ensures the pmtud state is not stuck in error
CI Tested
> LIT-166: on error retry pmtu check after 1 minute

- public/he.h
- src/he/conn.c
- src/he/frag.c
- src/he/frag.h
- src/he/he_internal.h
- src/he/msg_handlers.c
- src/he/ssl_ctx.c
- src/he/ssl_ctx.h
- test/he/test_conn.c
- test/he/test_conn_connect.c
- test/he/test_frag.c
- test/he/test_msg_handlers.c
- test/he/test_ssl_ctx.c
Added a new API to allow implementation customise the fragmentation table size.
Reduce memory usage on certain devices.
Unit tested.
> LIT-197 Make fragment table size configureable

- windows_32.yml
- windows_64.yml
- wolfssl/0005-AES-GCM-ARM64-Fix-clobber-lists.patch
Adds a new wolfSSL patch for an AES ARM64 assembly issue
This fixes the an issue on our router platform
Patch was manually tested on Aircove
> wolfssl: add patch for AES-ARM64 asm bug

- src/he/conn.c
- src/he/flow.c
- test/he/test_conn.c
- test/he/test_flow.c
Lightway Core should generate both a `HE_EVENT_SECURE_RENEGOTIATION_STARTED` and a `HE_EVENT_SECURE_RENEGOTIATION_COMPLETED` events when doing secure renegotiation. 
When adding DTLS v1.3 support in PR https://github.com/expressvpn/lightway-core/pull/76, the behaviour was accidentally broken and only a `HE_EVENT_SECURE_RENEGOTIATION_COMPLETED` event was generated if the connection is using DTLS v1.3.
This PR introduced a behaviour change to TLS 1.3 that generates HE_EVENT_SECURE_RENEGOTIATION_STARTED & HE_EVENT_SECURE_RENEGOTIATION_COMPLETED events when rekeying. The purpose is to make the rekeying activity explicit (e.g. monitoring in metrics) and consistent with DTLS. It's not perfect as the "key renegotiation" and "key update" are technically two different implementation in the RFC …
> LIT-279 conn: fix missing renegotiation events for dtls 1.3 and tls 1.3 connections

- README.adoc
Fixed the link to pre-commit.com as it was in Markdown form; the README is in adoc.
It's nice to be able to click on links.
I clicked Preview. It looked 👌 to me!
> readme: fix pre-commit link

- .github/CODEOWNERS
This simplifies management of permissions for ExpressVPN team members, as we can use this Github team across multiple repos as a single source of truth.
> Define CODEOWNERS as a Github team

- src/he/pmtud.h
RFC 8899 recommends the base PLPMTU to be 1200, but in our tests we found 1250 is better in terms of speed and stability. This change is likely to have effect only on networks with small MTUs.
Changed BASE_PLPMTU from 1200 to 1250.
CI tested
> CVPN-748 Enhance PMTUD Stability

- .github/workflows/ci.yml
- ios/Lightway/build-xcframework.sh
Steps in Github Actions recently began failing, one for iOS due to a case mismatch in a build script, and one for macOS due to Github changing its runners for `macos-latest` from x86 to arm64, conflicting with our build script.
Two changes:
- Change `macos-latest` to `macos-13` to use x86 hardware for our x86 build script
- Correct case mismatch in iOS build script
See [link 1](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) and [link 2](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) for details on recent changes to Github runners.
Verify Github Actions completes successfully
> CVPN-934 Fix Apple CI issues

- src/he/utils.c
- src/he/utils.h
- test/he/test_utils.c
Adding a helper function to help perform strncpy and null termination in one go.
`strncpy` has a pitfall that `dst` will not be null terminated if there is no null byte in the first `dst_size` bytes of the array pointed to by `src`. Therefore, this PR is adding a helper function.
CI Tested.
> utils: add helper function he_safe_strncpy

- public/he.h
In order for a function to be available publicly, it has to be added to the file `he.h` too. The he.h file is auto-generated by running the command `earthly +public-header`
CI Tested
> public-header: Add helper function he_safe_strncpy

- .github/workflows/ci.yml
- Earthfile
Simplifies some CI and gets rid of some nodejs warnings about actions
Cleanup some of the existing issues and to ensure it continues working as github runners get updated
CI Tested
> CI Improvements

- include/he.h
- public/he.h
- src/he/conn.c
- src/he/ssl_ctx.c
- test/he/test_conn.c
- test/he/test_conn_connect.c
- test/he/test_ssl_ctx.c
Allow lightway servers to accept higher security level when using hybrid Kyber KEM in UDP mode.
Used a feature in WolfSSL to allow a server to process a fragmented second/verified (one containing a valid cookie response) ClientHello message
Set which curve groups is accepted by the servers and their preference. 
Allow both UDP and TCP connections to be protected with post-quantum crytopgrahy at the highest available level
Allow UDP connection to use hybrid ML-KEM 1024 in the future
CI + unit test
Tested with a  `xv-helium-server`  with new lightway-core with `xv-helium-cli` that has OLD (the first connection) and NEW (the second connection) lightway-core:
> CVPN-245 Support hybrid kyber level 5 in UDP

- windows/wolfssl.vcxproj
Fix linking issues when we are building windows client applications. There were four unresolved functions, which was found in `wolfcrypt\src\port\liboqs\liboqs.c`
It was missing after we have bumped WolfSSL to 5.7.4
> Add missing module in windows build

- unix.yml
Ceedling/CMock cannot find ssl.h when we run ceedling test on a dev machine
```
Test 'test_conn.c'
------------------
Generating include list for fake_dispatch.h...
Generating include list for frag.h...
Generating include list for wolf.h...
Generating include list for pmtud.h...
ERROR: Found no file 'ssl.h' in search paths.
rake aborted!
```
Includes the ssl file for UNIX system from now on
Ran ceedling tests locally with the error gone
> Include ssl.h for cmock/ceedling

- 3rd_party_deps.yml
- ios/autotools-ios-helper.sh
- src/he/ssl_ctx.c
- test/he/test_ssl_ctx.c
- windows/wolfssl-user_settings-32.h
- windows/wolfssl-user_settings-64.h
- windows/wolfssl-user_settings-arm-64.h
Add ML-KEM groups when we are compiling WolfSSL.
Server supports ML-KEM and Kyber simultaneously. 
Use officially approved standard ML-KEM from NIST to strengthen security
Tested with a new helium server running locally and it can connect with:
1. Lightway C client with liboqs
2. Lighway C client w/o liboqs
3. New lightway rust without liboqs
Will add integration tests in helium-server once the client also migrates to ML-KEM
> CVPN-1636 Supports both ML-KEM and Kyber in server

- windows_32.yml
- windows_64.yml
- windows_arm64.yml
- wolfssl/0007-fix-kyber-prf-non-avx2.patch
The patch is from:
https://github.com/wolfSSL/wolfssl/pull/8306
This patch fixes an issue where older CPUs, with no AVX2 support, fail to handshake Kyber/ML-KEM.
Tested a new server with this fix built in. Old and new clients can indeed connect to it.
> CVPN-1681 Fix failed Kyber/ML-KEM handshake with non-AVX2 CPU

- .github/workflows/ci.yml
- Earthfile
Ceedling has officially released v1.0.0, which contains quite a bit of breaking changes. This commits updates CI and Earthfile to specify which version of ceedling to install to ensure the CI doesn't fail.
Fix failing CI and Earthile
CI
> Force Ruby gem to install v0.31.1 ceedling

- windows_32.yml
- windows_64.yml
- windows_64_multithread.yml
- windows_arm64.yml
- wolfssl/0008-intel-illegal-instruction.patch
- wolfssl/0009-reverse-only-with-avx12.patch
Fix illegal instruction on older desktop CPUs. Applied the 2 PRs provided by WolfSSL to fix this issue.
Prevent clients that are using older CPU from crashing
- Tested it on the platform that was not working originally and verified the 2 fixes work, and can indeed connect to our VPN servers
- Passed integration test
> CVPN-1725 Fix illegal instruction error on older CPUs

- windows_32.yml
- windows_64.yml
- windows_64_multithread.yml
- windows_arm64.yml
- wolfssl/0010-CVPN-1945-Lower-max-mtu-for-DTLS-1.3-handshake-message.patch
During the DTLS 1.3 handshake, large post-quantum certificates are exchanged. While DTLS supports message fragmentation, the first packet in the exchange remains extremely close to the MTU limit—just 15 bytes of headroom in the worst-case scenario (e.g., PPPoE or PPPoA networks). This minimal buffer leads to fragmentation on many networks despite the use of handshake fragmentation.
We observed that the current fragmentation behavior splits packets in a ~95/5 ratio, resulting in a large first packet and a tiny second one. This causes the first packet to be fragmented anyway, defeating the purpose of the feature.
This patch modifies the `Dtls13SendFragmentedInternal()` function in `dtls13.c` to reduce the maximum fragment size by 500 bytes:
```c
maxFragment = wolfSSL_GetMaxFragSize(ssl, …
```
> CVPN-1945 Add patch MTU fix patch file and apply it

- src/he/msg_handlers.c
- test/he/test_msg_handlers.c
The memory bound check had used `he_msg_auth_hdr_t` instead of `he_msg_auth_buf_t` or `he_msg_auth_token_t` struct in the auth flow.
The difference between the structs `he_msg_auth_buf_t` and `he_msg_auth_hdr_t` is 2.
This causes memory bounding logic to fail, allowing malicious requests with additional 2 bytes in length to continue. (ex: actual buf: 2 bytes, buf_length: 4)
But since we use local stack buffer which is reseted on every packet, the bytes sent to the callback could only be having 0 values.
https://github.com/expressvpn/lightway-core/blob/d51702d8f8bd37874e5e70da434bf22930a6b48a/src/he/flow.c#L464
Fix this by using the correct struct in bound checking.
Tests which were added in first commit will pass now after adding fix.
This bug is reported through BugCrowd
Added unit tests
> CVPN-2035: Fix using correct struct for validating length
