docs/antora.yml
docs/modules/ROOT/pages/faq.adoc
docs/modules/ROOT/pages/intro.adoc

* Added an FAQ document
* Cleaned up legacy version in Antora configuration
Viewed in local Antora testbed, content approved..

Add FAQ document, cleanup versions

---

CODE_OF_CONDUCT.adoc
CONTRIBUTING.adoc

- Adding CODE_OF_CONDUCT.adoc
- Adding Code of Conduct link to CONTRIBUTING.adoc

adding code-of-conduct

---

.github/CODEOWNERS

Updating CODEOWNERS to add [expressvpn-tom-l](https://github.com/expressvpn-tom-l)

Adding expressvpn-tom-l to CODEOWNERS

---

src/he/config.c
src/he/conn.c
src/he/flow.c
src/he/ssl_ctx.c
src/he/wolf.c
test/he/test_config.c
test/he/test_conn.c
test/he/test_flow.c
test/he/test_ssl_ctx.c

As part of best practices, we conduct regular penetration tests and code reviews. The issues identified in this PR are part of this continuous effort. The issues identified here are part of the function contract (for example a valid `he_conn_t * conn` is required for all of the getter and setter methods) but we are keen to bring these functions in line with the rest of our code base.
* Check all pointer parameters in WolfSSL IO callbacks for NULL pointers. These are set internally by Lightway and so in our usage, these cannot actually be NULL
Resolves any issues found as part of our ongoing testing as well as improving consistency across the code base.
All changes have been verified with `earthly +test` to ensure no breaking changes to the API.

Add various security enhancements

---

ios/autotools-ios-helper.sh

* Fixed iOS compiler issues when build WolfSSL v5.2.0
* Fixed issues reported by `shellcheck`
* Removed code that build macOS binaries unnecessarily
The changes have been verified with `ceedling project:ios` on a Mac.

Clean up and simplify ios build script for WolfSSL

---

src/he/wolf.c
test/he/test_wolf.c

Fixes a bug that prevents DTLS connections from connecting
Tested with our app directly

wolf: return want read if incoming data is null

---

AUTHOR.adoc

Add Raihaan as an author given all the code and improvements he is committing.
Update AUTHORS.adoc

Add Raihaan as an author

---

src/he/conn.h
test/he/test_conn.c

Add some missing tests for he_conn_t
Build has been ran with `earthly +all` locally to test

conn: Test improvements

---

unix.yml
windows_32.yml
windows_64.yml

Use version `5.3.0-stable` of WolfSSL.
Brings WolfSSL up to date. See WolfSSL 5.3.0 release notes for all changes: https://github.com/wolfSSL/wolfssl/releases/tag/v5.3.0-stable
All tests passed on Github CI.

Upgrade WolfSSL to 5.3.0

---

docs/modules/ROOT/pages/design_overview.adoc
docs/modules/ROOT/pages/faq.adoc
docs/modules/ROOT/pages/intro.adoc

docs: trivial typo and spelling fix in documentations

---

include/he.h
src/he/flow.c

Fix some documentation and remove extra memset
Clarifies the documentation and removes unneeded work
Tested via CI

Misc cleanups

---

.github/workflows/ci.yml
ios/Lightway/Lightway.xcodeproj/project.pbxproj
ios/Lightway/build-xcframework.sh
ios/autotools-ios-helper.sh

ios: Build iOS binaries on CI

---

.github/workflows/ci.yml
android/android_env.sh
unix.yml
windows_32.yml
windows_64.yml

Adds android CI
This ensures that all our supported platforms will continue to build
As this is a CI change, CI is expected to pass

android: Add CI for android platform

---

.github/workflows/ci.yml
android.yml
android/conversion.patch
linux_386.yml
unix.yml
windows_32.yml
windows_64.yml

Update to the latest wolfSSL we added an extra patch for Android to avoid an issue in this release
The update addresses some security issues in WolfSSL
Tested wolfcrypt manually for x64

wolfssl: update wolfssl to v5.5.0 with patch for Android

---

src/he/msg_handlers.c
test/he/test_msg_handlers.c

Corrects the packet size checks.
We also adjust the error returned to be in line with server config's error code.
Fixes a potential OOB read.
This code has autotests

msg_handlers: correct message size checks

---

android.yml
ios/autotools-ios-helper.sh
linux.yml
linux_386.yml
linux_arm.yml
macos.yml
macos_arm64.yml
unix.yml
windows/wolfssl-user_settings-32.h
windows/wolfssl-user_settings-64.h
windows_32.yml
windows_64.yml

Update wolfssl to the latest
Keeps our dependencies up to date
CI Autotests

wolfssl: update wolfssl to v5.5.4

---

.gitignore

This directory is created automatically by vscode. We never want to commit this so we should ignore it.
Will no longer show the tree as dirty
Trivial change, does not require testing

chore: ignore .vscode/ directory

---

include/he_plugin.h
public/he.h
public/he_plugin.h
src/he/plugin_chain.h

doc: add documentation to helium plugin apis

---

.github/workflows/ci.yml

Bump Earthly to v0.6.30 on CI.
Maintenance.
N/A

ci: bump earthly v0.6.30

---

ios.yml
linux.yml
linux_386.yml
linux_arm.yml
macos.yml
macos_arm64.yml
windows_32.yml
windows_64.yml

Applys our #72 fix in the prebuild step to prevent the double application issue
Cleaner implementation overall
CI will exercise this codepath

build: apply patch in pre_build step

---

ios.yml
linux.yml
linux_386.yml
linux_arm.yml
macos.yml
macos_arm64.yml
windows_32.yml
windows_64.yml

Reverts #77 as the tool only works on a global level
Does not apply the fix we want
Revert so does not require specific testing

Revert "Merge pull request #77 from expressvpn/wolfssl-patch-fix"

---

windows/wolfssl.vcxproj

Syncs the windows project to the wolfssl latest
This fixes an issue when a user builds with x64 platform.
Tested with internal builds of our libraries.

win: update windows project

---

public/he.h
src/he/conn.h
windows_32.yml

Fix typos found by codespell

---

unix.yml
windows_32.yml
windows_64.yml

Update WolfSSL v5.6.3-stable and revert the changes to linux/arm builds. Changes: https://github.com/wolfSSL/wolfssl/releases/tag/v5.6.3-stable
Keeping dependencies up-to-date.
Tested on CI.

wolfssl: update wolfssl to v5.6.3-stable

---

.github/workflows/ci.yml
ios/Lightway/Lightway.xcodeproj/project.pbxproj
ios/autotools-ios-helper.sh
tvos.yml

Adding tvOS support.
[Apple TV will get VPN access in tvOS 17](https://www.androidauthority.com/apple-tv-vpn-3332258/).
The change is only experimental as it's only built on CI. It's not tested on actual Apple TV device yet.

Add tvOS support

---

.github/CODEOWNERS

Adding Andre L as codeowner for entire repo

---

.github/workflows/ci.yml
android.yml
ios.yml
linux.yml
linux_386.yml
linux_arm.yml
macos.yml
macos_arm64.yml
tvos.yml
unix.yml
windows_32.yml
windows_64.yml

Use tag over hash when building. This causes the clone to be shallow resulting in a faster clone
See:
https://github.com/ThrowTheSwitch/Ceedling/blob/8d3605cac60ca981a63df4c119be1060875015c6/plugins/dependencies/lib/dependencies.rb#L120-L131
Faster build times
CI Tested

Improve build times

---

.github/workflows/ci.yml

Add CI for M1 and newer macs
Improves our CI coverage
CI tested

ci: add CI for arm64 macs

---

android.yml
ios.yml
linux.yml
linux_386.yml
linux_arm.yml
macos.yml
macos_arm64.yml
tvos.yml
windows_32.yml
windows_64.yml
wolfssl/0001-DoHelloVerifyRequest-only-do-DTLS-1.3-version-check.patch
wolfssl/0002-DTLS-1.3-move-state-machine-forward-when-HVR-receive.patch
wolfssl/0003-DtlsShouldDrop-don-t-ignore-app-data-sent-before-a-S.patch
wolfssl/0004-Dtls13GetRnMask-Correctly-get-chacha-counter-on-BE-s.patch

Fixes an issue with DTLS1.3 and chacha20.
Chacha20 does not work without this patch
Tested manually with internal tooling

wolfssl: add chacha20 fix patch

---

public/he.h
src/he/utils.c
src/he/utils.h
test/he/test_utils.c

Utility function to easily stringify an enum
Makes logging easier and more clear
Auto tests

utils: add protocol_name utility function

---

public/he.h
src/he/conn.c
src/he/conn.h
test/he/test_conn.c

Function to show the key exchange curve
Useful for debugging which key-exchange mechanism was used
Tested with lightway-laser

conn: add a function to get curve name

---

include/he.h
public/he.h
src/he/he_internal.h

Making the `he_auth_type_t` enum public.
Allow client & server access the enum directly.
Unit tested on CI.

VAN-159 Making he_auth_type_t enum public

---

public/he.h
src/he/conn.c
src/he/conn.h
test/he/test_conn.c

Add a new public api: `he_conn_get_protocol_version` for getting the current protocol set in the connection.
Unit tested.

VAN-160 Add he_conn_get_protocol_version

---

.github/workflows/ci.yml

Bump Earthly to v0.7.20 on CI.
Maintenance.
CI.

ci: update Earthly to v0.7.20

---

.pre-commit-config.yaml
Earthfile
README.adoc
src/he/flow.c
src/he/plugin_chain.c
test/he/test_ssl_ctx.c
test/he/test_wolf.c
test/support/test_defs.h
windows/wolfssl-user_settings-32.h
windows/wolfssl-user_settings-64.h

Support running common dev commands via `earthly`. Also added `pre-commit` check to enforce code formatting.
Quality of life improvement.
N/A.

Add Earthly commands for local development and pre-commit checks

---

test/he/test_conn.c
test/he/test_msg_handlers.c
test/he/test_ssl_ctx.c

Fix compiler warnings.
Maintenance.
CI.

Fix multiple compiler warnings in tests

---

ios/Lightway/Lightway.xcodeproj/project.pbxproj
src/he/flow.c
src/he/msg_handlers.c
src/he/msg_handlers.h
src/he/network.c
src/he/network.h
test/he/test_flow.c
test/he/test_msg_handlers.c
test/he/test_network.c

Add Network header for some network functions
This deduplicates some IP version check code.
We are also doing this in preparation for PMTUD feature
Unit tested

network: refactor some code into network header

---

.github/workflows/ci.yml

Reduces duplication in CI configurations
Simplifies CI
CI Tested

ci: reduce duplication in CI configs

---

Earthfile
public/he.h
src/he/conn.c
src/he/conn.h
src/he/pmtud.h
src/he/ssl_ctx.h
test/he/test_conn.c

Fix some minor bugs.
Maintenance.
Unit tested.

misc: minor bug fixes

---

windows/wolfssl.vcxproj

Adding back missing files to wolfssl.vcxproj which was accidentally removed in previous PR.
Tested in both CI and client-side builds.

wolfssl: fix windows build

---

src/he/flow.c

The `effective_pmtu` is the largest packets size we can send in a `he_msg_data_t` message,
but since `he_msg_data_frag_t` has slightly more overhead, we cannot use the `effective_pmtu` as
the fragment size directly.
Bug fix.
Tested manually.

LIT-135 Fix fragmentation bugs

---

src/he/pmtud.c
src/he/pmtud.h
test/he/test_pmtud.c

We retry the PMTUD search algorithm every 10 minutes once completed to ensure
the value is always accurate.
Keeps this value always accurate
Tested with unit tests

LIT-167: Retry PMTUD search once completed

---

android.yml
ios.yml
ios/autotools-ios-helper.sh
linux.yml
linux_386.yml
linux_arm.yml
linux_arm64.yml
linux_arm_no_pqc.yml
macos.yml
macos_arm64.yml
tvos.yml
windows_32.yml
windows_64.yml
wolfssl/0001-tls-return-immediately-if-kyber_id2type-fails.patch
wolfssl/0002-SP-ARM64-P-256-mark-functions-as-SP_NOINLINE.patch

Fixes bugs with wolfSSL 5.6.4
Patches included:
* 0001 - patch for pqc crash fix
* 0002 - patch for arm64 assembly issues
Prevents our workarounds around these issues
iOS was tested manually
@xv-ian-c has the PQC patch running on one of his systems

wolfssl: add wolfssl patches

---

src/he/pmtud.c
test/he/test_pmtud.c

Retry probing in completed state. This fixes an issue where the probe is not retried after the first in completed state
Continuous checking of the PMTUD value
New Unit tests have been added

pmtud: retry successful probe in completed state

---

3rd_party_deps.yml
tvos.yml

Update liboqs 0.9.1 which contains bug and security fixes.
Changes: https://github.com/open-quantum-safe/liboqs/releases/tag/0.9.1
Keeping dependencies up to date.
* Auto tested using Lightway server / client integration test infrastructure
* Manual tested on iOS 16 (iPhone 8) and Android 13 (Pixel 5a)

LIT-259 update liboqs to 0.9.1

---

.github/workflows/ci.yml
linux_riscv64.yml

Adding RISC-V support.
CI tested.

build: adding experimental risc-v support

---

public/he.h
src/he/conn.c
src/he/conn.h
src/he/core.c
src/he/flow.c
src/he/he_internal.h
test/he/test_conn.c
test/he/test_core.c
test/he/test_flow.c

Add additional method for wolfSSL errors
Help debugging and tracking unknown wolfSSL errors.
CI tested.

conn: add method to get detailed SSL errors

---

3rd_party_deps.yml

Update liboqs 0.9.2 which contains security fixes.
Changes: https://github.com/open-quantum-safe/liboqs/releases/tag/0.9.2
Keep 3rdparty dependencies up to date.
CI tested.

liboqs: bump liboqs to v0.9.2

---

src/he/pmtud.c
src/he/pmtud.h
test/he/test_pmtud.c

This reduces the number of probes when doing path-mtu discovery.
Unit tested.

CVPN-165 Start PMTUD from 1200 MTU

---

.github/workflows/ci.yml
windows/ceedlingarm64.bat
windows/wolfssl-user_settings-arm-64.h
windows/wolfssl.vcxproj
windows_arm64.yml

Adds an arm64 build for windows
To add native arm64 support for the windows platform
CI Tested

Windows ARM64 build

---

.github/workflows/ci.yml
3rd_party_deps.yml
android.yml
ios.yml
ios/autotools-ios-helper.sh
linux.yml
linux_386.yml
linux_arm.yml
linux_arm64.yml
linux_arm_no_pqc.yml
linux_riscv64.yml
macos.yml
macos_arm64.yml
test/support/wolfssl_testable_types.h
tvos.yml
windows/wolfssl-user_settings-32.h
windows/wolfssl-user_settings-64.h
windows/wolfssl-user_settings-arm-64.h
windows_32.yml
windows_64.yml
windows_arm64.yml
wolfssl/fix-falcon-dilithm-flags.patch

Bump WolfSSL to 5.7.4 for bug fixes
Enabled experimental settings in config or WOLFSSL_EXPERIMENTAL_SETTINGS flag as using liboqs require this setting to be turned on from now on
Added a patch to fix the incorrect flags being set in WolfSSL.
No breaking changes from WolfSSL's change logs
Fix WolfSSL bugs and allow us to patch ML-KEM and Kyber support in a future PR
CI and Unit tests

CVPN-1309 Bump WolfSSL to 5.7.4

---

.gitignore
README.adoc

ceedling is pre-releasing v1.0.0, however there is some breaking changes introduced by it. Specifying the required ceedling version here for clarity. 
Also ignore the local `.ruby-version` in gitignore as some of the devs are using `rbenv` to install older ruby (as v0.31.1 is incompatible with ruby 3)

Update docs to specify which version of ceedling we are using

---

src/he/conn.c
test/he/test_conn_connect.c

Switch the client to use hybrid ML-KEM from WolfSSL
Note: Will release this once we have fully rollout all the new servers
Use the latest and officially approved standard of post-quantum cryptography.
1. Passed coverage test as well
2. Tested with a locally built android client and client with the new server, which does indeed uses ML-KEM.

CVPN-1420 Switch client to use ML-KEM from WolfSSL

---

.github/workflows/ci.yml

Pin ruby versions as they are updating it see https://github.com/actions/runner-images/issues/11345
Fixes CI
CI only

ci: pin ruby version on CI
